CHEF: Madhvi Sharma.A

Recipe : besan-ke-ladoo

INFORMATION about besan-ke-ladoo:

=> Besan laddu is a popular Indian sweet dish made of besan (gram flour), sugar, and ghee. 
=> Besan is roasted in ghee till golden brown appearance with a nutty fragrance.
=> Then sugar is added to it. 
=> Sweet balls are then made from this mixture. 
=> It has a long shelf life.
=> It is often served at festivals, family events and religious occasions in India.

THANK YOU..